server:
  port: ${SPRING_APPLICATION_PORT}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        security.oauth2: TRACE

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB}
  security:
    oauth2:
      authorizationserver:
        client:
          account-client-oauth2:
            registration:
              client-id: ${OAUTH2_ACCOUNT_CLIENT_ID}
              client-secret: ${OAUTH2_ACCOUNT_CLIENT_SECRET}
              client-authentication-methods: ${OAUTH2_ACCOUNT_CLIENT_AUTHENTICATION_METHODS}
              authorization-grant-types: ${OAUTH2_ACCOUNT_CLIENT_AUTHORIZATION_GRANT_TYPES}
              scopes: ${OAUTH2_ACCOUNT_CLIENT_SCOPES}
          notification-client-oauth2:
            registration:
              client-id: ${OAUTH2_NOTIFICATION_CLIENT_ID}
              client-secret: ${OAUTH2_NOTIFICATION_CLIENT_SECRET}
              client-authentication-methods: ${OAUTH2_NOTIFICATION_CLIENT_AUTHENTICATION_METHODS}
              authorization-grant-types: ${OAUTH2_NOTIFICATION_CLIENT_AUTHORIZATION_GRANT_TYPES}
              scopes: ${OAUTH2_NOTIFICATION_CLIENT_SCOPES}
          experience-client-oauth2:
            registration:
              client-id: ${OAUTH2_EXPERIENCE_CLIENT_ID}
              client-secret: ${OAUTH2_EXPERIENCE_CLIENT_SECRET}
              client-authentication-methods: ${OAUTH2_EXPERIENCE_CLIENT_AUTHENTICATION_METHODS}
              authorization-grant-types: ${OAUTH2_EXPERIENCE_CLIENT_AUTHORIZATION_GRANT_TYPES}
              redirect-uris: ${OAUTH2_EXPERIENCE_CLIENT_REDIRECT_URIS}
              scopes: ${OAUTH2_EXPERIENCE_CLIENT_SCOPES}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URI}/eureka/