server:
  port: ${SPRING_APPLICATION_PORT}
#  servlet.context-path: /api

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        security.oauth2: TRACE

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  security:
    oauth2:
      client:
        registration:
          account-client-oauth2-client-credentials:
            provider: spring
            client-name: ${OAUTH2_ACCOUNT_CLIENT_NAME}
            client-id: ${OAUTH2_ACCOUNT_CLIENT_ID}
            client-secret: ${OAUTH2_ACCOUNT_CLIENT_SECRET}
            client-authorization-method: ${OAUTH2_ACCOUNT_CLIENT_AUTHENTICATION_METHOD}
            authorization-grant-type: ${OAUTH2_ACCOUNT_CLIENT_AUTHORIZATION_GRANT_TYPE}
            scope: ${OAUTH2_ACCOUNT_CLIENT_SCOPES}
          notification-client-oauth2-client-credentials:
            provider: spring
            client-name: ${OAUTH2_NOTIFICATION_CLIENT_NAME}
            client-id: ${OAUTH2_NOTIFICATION_CLIENT_ID}
            client-secret: ${OAUTH2_NOTIFICATION_CLIENT_SECRET}
            client-authorization-method: ${OAUTH2_NOTIFICATION_CLIENT_AUTHENTICATION_METHOD}
            authorization-grant-type: ${OAUTH2_NOTIFICATION_CLIENT_AUTHORIZATION_GRANT_TYPE}
            scope: ${OAUTH2_NOTIFICATION_CLIENT_SCOPES}
        provider:
          spring:
            issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI}

gateway:
  base-uri: ${GATEWAY_URI}
account:
  base-uri: ${ACCOUNTS_URI}
notification:
  base-uri: ${NOTIFICATION_URI}

feign:
  client:
    config:
      default:
        loggerLevel: full

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URI}/eureka/