server:
  port: ${SPRING_APPLICATION_PORT}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    #    server:
#    #      waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    prefer-ip-address: true
