spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: route-experience
          uri: ${EXPERIENCE_URI:http://localhost:8080}/
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        registration:
          experience-client-oauth2-authorization-code:
            provider: spring
            client-id: ${OAUTH2_EXPERIENCE_CLIENT_ID:experience-client}
            client-name: ${OAUTH2_EXPERIENCE_CLIENT_NAME:experience-client-oauth2-authorization-code}
            client-secret: ${OAUTH2_EXPERIENCE_CLIENT_SECRET:secret-experience}
            #            client-authorization-method: ${OAUTH2_EXPERIENCE_CLIENT_AUTHENTICATION_METHOD}
            authorization-grant-type: ${OAUTH2_EXPERIENCE_CLIENT_AUTHORIZATION_GRANT_TYPE:authorization_code}
            redirect-uri: ${OAUTH2_EXPERIENCE_CLIENT_REDIRECT_URI:{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}}
            #            redirect-uri: ${OAUTH2_EXPERIENCE_CLIENT_REDIRECT_URI:http://experience:8080/login/oauth2/code/experience-client-oauth2-authorization-code}
            scope: ${OAUTH2_EXPERIENCE_CLIENT_SCOPES:openid, profile, experience.read, experience.write}
        provider:
          spring:
            issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://localhost:9000}

#experience:
#  base-uri: ${EXPERIENCE_URI:https://experience-service-piggy-metric-dev-dqminh2810.cloud.okteto.net}
#  base-uri: ${EXPERIENCE_URI:http://experience-service:8080}

#eureka:
#  client:
#    serviceUrl:
#      #defaultZone: ${REGISTRY_URI:https://registry-piggy-metric-dev-dqminh2810.cloud.okteto.net}/eureka/
#      defaultZone: ${REGISTRY_URI:http://localhost:8761}/eureka/