spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://localhost:9000}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://localhost:9000}

gateway:
  base-uri: ${GATEWAY_URI:http://localhost:8000}
account:
  base-uri: ${ACCOUNTS_URI:http://localhost:8081}
notification:
  base-uri: ${NOTIFICATION_URI:http://localhost:8082}

feign:
  client:
    config:
      default:
        loggerLevel: full

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${REGISTRY_URI:http://localhost:8761}/eureka/