server:
  port: ${SPRING_APPLICATION_PORT:8081}

logging:
  level:
    root: INFO
    org:
      apache:
        http: DEBUG
      springframework:
        web: DEBUG
        security: DEBUG
        security.oauth2: TRACE
    reactor:
      netty:
        http:
          server: DEBUG
          client: DEBUG

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:account-service}
  data:
    mongodb:
      host: ${MONGO_DB_HOST:account-mongodb}
      port: ${MONGO_DB_PORT:25000}
      username: ${MONGO_DB_USERNAME:user}
      password: ${MONGO_DB_PASSWORD:password}
      database: ${MONGO_DB:piggymetrics}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://auth-service:9000}
      client:
        provider:
          spring:
            issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://auth-service:9000}
#      client:
#        registration:
#          notification-client-oauth2-client-credentials:
#            provider: spring
#            client-name: ${OAUTH2_NOTIFICATION_CLIENT_NAME}
#            client-id: ${OAUTH2_NOTIFICATION_CLIENT_ID}
#            client-secret: ${OAUTH2_NOTIFICATION_CLIENT_SECRET}
#            client-authorization-method: ${OAUTH2_NOTIFICATION_CLIENT_AUTHENTICATION_METHOD}
#            authorization-grant-type: ${OAUTH2_NOTIFICATION_CLIENT_AUTHORIZATION_GRANT_TYPE}
#            scope: ${OAUTH2_NOTIFICATION_CLIENT_SCOPES}
#          notification-client-oauth2-authorization-code:
#            provider: spring
#            client-name: ${OAUTH2_NOTIFICATION_CLIENT_NAME}
#            client-id: ${OAUTH2_NOTIFICATION_CLIENT_ID}
#            client-secret: ${OAUTH2_NOTIFICATION_CLIENT_SECRET}
#            client-authorization-method: ${OAUTH2_NOTIFICATION_CLIENT_AUTHENTICATION_METHOD}
#            authorization-grant-type: ${OAUTH2_NOTIFICATION_CLIENT_AUTHORIZATION_GRANT_TYPE}
#            redirect-uri: ${OAUTH2_NOTIFICATION_CLIENT_REDIRECT_URI}
#            scope: ${OAUTH2_NOTIFICATION_CLIENT_SCOPES}

notification:
  base-uri: ${NOTIFICATION_URI:http://notification-service:8082}

feign:
  client:
    config:
      default:
        loggerLevel: full

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${REGISTRY_URI:http://registry:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus