server:
  port: ${SPRING_APPLICATION_PORT:8083}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:statistic-service}
  data:
    mongodb:
      host: ${MONGO_DB_HOST:statistic-mongodb}
      port: ${MONGO_DB_PORT:27000}
      username: ${MONGO_DB_USERNAME:user}
      password: ${MONGO_DB_PASSWORD:password}
      database: ${MONGO_DB:piggymetrics}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_PROVIDER_ISSUER_URI:http://auth-service:9000}

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${REGISTRY_URI:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus